--- # Loop Playbook
- hosts: demo
  user: ansible
  become: yes
  connection: ssh
  tasks: 
    - name: installing nginx
      user: name='{{item}}' state=present
      with_items:
              - abc
              - ijk
              - pqr
              - xyz
- hosts: demo
  user: ansible
  become: yes
  connection: ssh
  vars:
    pkg:
     - vsftpd
     - tree
  tasks: 
    - 
      name: 'installing'
      apt: name="{{ item }}" state=present
      with_items: "{{ pkg }}"